### PR TITLE
Added code to convert Paise to Rupee

### PR DESCRIPTION
**Pull request by AbhinavPrabhat01**
Required code added for the conversion of currency.

### CODE REVIEW

**Comment by AbhinavPrabhat01** [comment]
Hello , I just created a PR can you check the file and suggest me anything that you want or if everything is fine then merge the repo.

Thanks

**Review by backendbuilderdev — APPROVED** [review]
@AbhinavPrabhat01 Everything `LGTM`

**Comment by backendbuilderdev** [comment]
@AbhinavPrabhat01 Congratulations on your first contributions in our repo.
Keep Contributing!

**Comment by AbhinavPrabhat01** [comment]
Hey @Pal-Sandeep  , can you tell me how much time it would take to merge my pull request to your repo.

**Pull request merged**
